### ISSUE TITLE
Add some pizza because pizza improves everything

### ISSUE THREAD

**Issue by cainy-a** [Cumcord/Cumcord#3]
Everything is better with pizza

![](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fthumbs.dreamstime.com%2Fz%2Fdelivery-pizza-man-cheerful-young-deliveryman-holding-pizza-box-isolated-white-43249646.jpg)

**Comment by MoltenCoreDev** [comment]
oik i approve
