### ISSUE TITLE
The repo name

### ISSUE THREAD

**Issue by nikeedev** [Cumcord/Cumcord#9]
Does the repo name means, the same what i think it is?

*Cum*cord......?

**Comment by lexisother** [comment]
Yes.

**Comment by nikeedev** [comment]
Why….

**Comment by lexisother** [comment]
Are you going to continue making useless comments or actually ask a serious question?

**Comment by yellowsink** [comment]
![image](https://user-images.githubusercontent.com/19270622/160278916-1c1f82dd-a924-4365-a633-51661a6d649c.png)

**Comment by nikeedev** [comment]
Im just a user, don’t need to be angry on me…

**Comment by nikeedev** [comment]
> ![image](https://user-images.githubusercontent.com/19270622/160278916-1c1f82dd-a924-4365-a633-51661a6d649c.png)

It is hilarious

**Comment by lexisother** [comment]
Deleting issue.
